language: ruby
jdk:
- oraclejdk8
rvm:
- 2.3.1
before_install:
- openssl aes-256-cbc -K $encrypted_bf0576e69c23_key -iv $encrypted_bf0576e69c23_iv
  -in etc/secrets -out ../secrets.tar -d
- "(cd ../ && tar xvf secrets.tar)"
- chmod 600 ../release.asc
- gpg --import ../release.asc
install:
- rvm use 2.3.1
- gem install bundler
- bundle install
script: buildr clean package mcrt:publish_if_tagged
git:
  depth: false
env:
  global:
  - secure: n+ATjhtAzzft9mRev9W/5O1gS0I8O4ijvH5itAXiVcXSg/PnNeZ0zTmGwpd7/avI417SvToufWtdNXoArUWEEYltzEXyCePKhrnOyPwgnwTp5Ak9jz+kcUEiVixPT3Uru6O9TNRZApceO62o6Dz48xGpziz2IYKHrvZi9KESP0H4PkW6/htvnTc5WD0ol+grju49BZVneb/X/QD3PJ9ZrX5s5tW5iqdpyt0YEnJh8hlJQPgYSHo6UrciKrlNoQbxKFbH6vNzMzzANkJHCk6YvrVhV3QHpqvnpYz6ZcTdV0LFYyZAtZKtNocwDSZ0noZpeSohLWKuJmIo6eXbsNM9ol+p5Fre2ua4hQNZJv6rB8Cj/n9svgB1dPr8S/0JNXxWzzQgnJD2yIMM07WmFIz1EQmw3/nvv9tAwIY2SaZcOppMxzZj6Ig2n/3D0mG6x/jWxVInKSiIbZW8mHHYTCBvjA2AN1Mq8jKY9NQyzVYvSX+8M1PtkSiHhpfYbejaRPcXTaBruq3vwUfHPJispisAMKXHjfFI/Z0TH1TloEX9WtFnj3M1n/6d7GX5uXbYblmhuM7nk1I+FDNHT1KndtSd/SJV7JErtnS1VsF1i51twe7T29MkAszyp7oqzCAToOrzzKf8BEu6zwgL0Ai59uCzDWXGy+f0q2VAvE+rxHlCVJg=
  - secure: HQrJprsGq2a1UQu8I638FdU2OSLwaXCDQo2mu5e6zWyrgy3ohZnW5cEeDAQ0IrWS32HKLIX5CEvRAfNPZSoHqLpQz6ih5ue5oDS8NYnhKyXt9IpNvvOaEI/iXI1UaD0No90Q74tPbVdna0NaZHLmIDx1PDpjJly1rqjbw3d9GDOB4BkHnU6HoS+0wYRkZzTxgCPQ8KJUrSkrKWAOJTIf2iG4FUGbjAjqFXAM/+PBErlEyduCoHGPSz8s8RQYvoygfGKrOy5fOIkZNc3UsiZwMPblYFUthqiJcebBUUjB5BiAx2cUxxKHQhNe79sbU9hd/UG8rLqxw+N0DN8MdvRUyMFeymaLVwo6QgxVfHyzL5f+MO02IdmVPJpSlPEULep54j5GJ9BeRETuHI4HnshV8pBjhtWt7+Ax6WOeX2EIiuRBEjI+/MP6Fy1PRYTPadvbkvZ3mEasCzgkz+wh74itKp0X/sjV3ezQwvAPfeRgeovhmd864v5fJ1hmpP3kmvrFl4AHUdZB/rmW8E28wKXW+bJv90BrQvW2gnb9TnguZsAWKHmRlvLO4DV40jl2nRtjaNU5OQ2QPIretk0Vljm64B8zccq1/K4wlUHqzTKORLp3j/3I1eqINrdUozXM3Nlah8I5u0FelTH/tZmVj3JWVASQhrMNdeX94nvYgk2qTds=
  - secure: r73tHuoGyJMnh8p4UxQDRAWGB4D3fAbgqDh1WG0r3DZB4S9Req8q7lnvObQw+vOQIzVQIOv2sC7SsdUkAQbDvheqqth3gwLJLLnBLwK9BLBruM8/K5hFhO46kg2mmsagducsnsuX0CsgqApSKJk0m/BcZXKtP/FsF560haOpi4lI6QyxFqtquaOXIieySmG9BlPAgvD9JL6qcn7O4dawDwxHYLhH8XCLJNGk3gMWzJSMpyMTn+RvQiZKnVTvZwSgkUD7XjjhdhjPySHXxUR0EGfOmd9Hfg4hkJc3rIx0Yv6AW0rtNVD8f36ARTfKkI7iOu9CcYeNHIjNRnEAhgDfCR5t5vsS63RFd52Mf2yoTE4ykHFsgVq10SNjt7ZMessKTX8XWAFsSKkTf4Tgquu+nTdnxy5EHW1VFBVO4jxtQvu1+VJIvXQrN1osjsxiMApD6ZNLrlXNntQpwmp2UZDYPgV+KGKUxoz8gtLoeK1Ech53B6nfgNXK+LJxndr8EY12NZP5/QLQSr/0r25gFx4zPSrQuc8lekLpqmUYjIN95EADeO3MDkK1c9RwCqvSSSW8LSqTLc8X3hSjJpl+9plRB2Sh1LyR3ODrI98dEMIyQyqJUsgZPNFbfPD9DdOyc+V7zmuFmRCEr7zhROTICvXM6LYK8uQ4F/AueLIO06VYQ24=
